# -*- coding: utf-8 -*-
# AssurCore -- Module de Courtage Assurance (Tunisie) -- IPF / Mansour Borchani

{
    'name': 'AssurCore -- Courtage & Assurance TN',
    'version': '17.0.1.3.0',
    'category': 'Insurance',
    'summary': 'Gestion de courtage assurance pour le marche tunisien.',
    'author': 'IPF',
    'website': 'https://www.facebook.com/perseverance.formation',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'account',
        'crm',
        'fleet',
        'contacts',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/menu_restrictions.xml',
        'data/insurance_data.xml',
        'data/smtp_config.xml',
        'data/email_templates.xml',
        'views/res_partner_views.xml',
        'views/insurance_company_views.xml',
        'views/insurance_commission_rule_views.xml',
        'views/insurance_policy_views.xml',
        'views/insurance_ocr_wizard_views.xml',
        'views/dashboard_views.xml',
        'views/insurance_receipt_views.xml',
        'views/insurance_claim_views.xml',
        'views/insurance_risk_views.xml',
        'views/insurance_operation_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/insurance_branch_views.xml',
        'views/insurance_mouvement_report_wizard_views.xml',
        'views/insurance_accounting_views.xml',
        'views/insurance_receipt_report.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            ('prepend', 'assurcore/static/src/scss/_variables.scss'),
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
