-- ==============================================================
-- Import PR_CODE_OPERATION → insurance_operation_type
-- EVO02
-- ==============================================================
BEGIN;
INSERT INTO insurance_operation_type
    (code_operation1, code_operation2, code_operation3, code_operation4,
     designation, libelle_honoraire, branche, risque,
     code_label, active, create_date, write_date)
VALUES
    ('TTT','A40','A41','000','Terme engin auto','A','engin','Termes','TTT/A40 — Terme engin auto',true,NOW(),NOW()),
    ('T  ','A40','A42','000','terme engin 2','A','engin','Termes','T  /A40 — terme engin 2',true,NOW(),NOW()),
    ('010','010','002','000','Terme Vie/Placement','Frais de dossier Terme vie','PLACEMENT','Termes','010/010 — Terme Vie/Placement',true,NOW(),NOW()),
    ('005','007','025','000','Police Grele','Honoraires souscription Police Grele','RISQUES AGRICOLES','Comptant','005/007 — Police Grele',true,NOW(),NOW()),
    ('003','005','100','000','Avenant Multirisques Pro.','Honoraires souscription Avenant Multirisque Professionnelle','MULTIRISQUES PROFESSIONNELLES','Comptant','003/005 — Avenant Multirisques Pro.',true,NOW(),NOW()),
    ('001','001','050','000','Police Auto 2 roues Ferme','Honoraires souscription police véhicule 2 roues ferme','AUTO','Comptant','001/001 — Police Auto 2 roues Ferme',true,NOW(),NOW()),
    ('005','001','100','000','Avenant Vol','Honoraires Souscription avenant Vol','RISQUES DIVERS','Comptant','005/001 — Avenant Vol',true,NOW(),NOW()),
    ('003','003','003','000','Avenant Incendie Simple','Honoraires Souscription Avenant Incendie Simple','INCENDIE','Comptant','003/003 — Avenant Incendie Simple',true,NOW(),NOW()),
    ('004','001','005','000','Police Facultés Terrestre','Honoraires Souscription Police Facultés Terrestre','TRANSPORT','Comptant','004/001 — Police Facultés Terrestre',true,NOW(),NOW()),
    ('001','001','005','000','Police Auto Ferme','Honoraires Souscription Police Auto Ferme','AUTO','Comptant','001/001 — Police Auto Ferme',true,NOW(),NOW()),
    ('009','005','009','000','Avenant Accidents Corporels','Honoraires souscription avenant accidents corporels','RISQUES DIVERS','Comptant','009/005 — Avenant Accidents Corporels',true,NOW(),NOW()),
    ('006','019','150','000','Police Décès','Honoraire Souscription Police Décès','RISQUES DIVERS','Comptant','006/019 — Police Décès',true,NOW(),NOW()),
    ('007','006','123','000','Avenant Tous Risques Ordinateurs','Honoraires avenant Tous Risques Ordinateurs','RISQUES SPECIAUX','Comptant','007/006 — Avenant Tous Risques Ordinateurs',true,NOW(),NOW()),
    ('004','500','300','000','Police Décès','Honoraires Police Décès','MALADIE','Comptant','004/500 — Police Décès',true,NOW(),NOW()),
    ('100','100','119','000','Police EUROP ASSISTANCE','Honoraires Souscription Police EUROP ASSISTANCE','ASSISTANCE','Comptant','100/100 — Police EUROP ASSISTANCE',true,NOW(),NOW()),
    ('008','501','502','000','Avenant Décès','Honoraires souscription avenant Décès','DECES','Comptant','008/501 — Avenant Décès',true,NOW(),NOW()),
    ('009','005','101','000','Avenant Tous Risques Engins','Honoraires Avenant Tous Risques Engins','RISQUES SPECIAUX','Comptant','009/005 — Avenant Tous Risques Engins',true,NOW(),NOW()),
    ('002','002','078','000','Avenant Police Temporaire Décès','Honoraires Avenant Police Temporaire Décès','VIE','Comptant','002/002 — Avenant Police Temporaire Décès',true,NOW(),NOW()),
    ('001','001','133','000','Police automobile usage Agricol','Honoraires souscription police automobile usage agricol','AUTO','Comptant','001/001 — Police automobile usage Agricol',true,NOW(),NOW()),
    ('001','001','768','000','Avenant Police Auto Flotte','Honoraires Avenant Police Auto Flotte','AUTO','Comptant','001/001 — Avenant Police Auto Flotte',true,NOW(),NOW()),
    ('005','400','541','000','Avenant Decès','Honoraires Avenant Decès','MALADIE','Comptant','005/400 — Avenant Decès',true,NOW(),NOW()),
    ('009','004','045','000','Avenant Tous Risques Chantiers','Honoraires Avenant Tous Risques Chantiers','RISQUES SPECIAUX','Comptant','009/004 — Avenant Tous Risques Chantiers',true,NOW(),NOW()),
    ('001','024','332','000','Avenant Police Auto Usage Agricole','onoraires Avenant Police Auto Usage Agricole','AUTO','Comptant','001/024 — Avenant Police Auto Usage Agricole',true,NOW(),NOW()),
    ('001','005','358','000','Avenant Police Auto Usage Utilitaire','Honoraires Avenant Police Auto Usage Utilitaire','AUTO','Comptant','001/005 — Avenant Police Auto Usage Utilitaire',true,NOW(),NOW()),
    ('001','055','332','000','Avenant Police Auto Taxi','Honoraires Avenant Police Auto Taxi','AUTO','Comptant','001/055 — Avenant Police Auto Taxi',true,NOW(),NOW()),
    ('001','055','339','000','Avenant Police Auto Transport Rural','Honoraires Avenant Police Auto Transport Rural','AUTO','Comptant','001/055 — Avenant Police Auto Transport Rural',true,NOW(),NOW()),
    ('001','559','778','000','Police Auto Transport Rural','Honoraires Police Auto Transport Rural',NULL,NULL,'001/559 — Police Auto Transport Rural',true,NOW(),NOW()),
    ('001','886','658','000','Liquidation primes et commissions au 31/12/2006','Liquidation primes et commissions au 31/12/2006','MALADIE','Comptant','001/886 — Liquidation primes et commissions au 31/12/2006',true,NOW(),NOW()),
    ('004','005','059','000','avenant liquidation primes/commissions +/- au 31/12/2006','Liquidation primes/commissions +/- au 31/12/2006','MALADIE','Comptant','004/005 — avenant liquidation primes/commissions +/- au 31/12/2006',true,NOW(),NOW()),
    ('001','001','001','000','Police Automobile','Honoraires souscription Police Automobile','AUTO','Comptant','001/001 — Police Automobile',true,NOW(),NOW()),
    ('001','001','002','000','Police Auto Flotte','Honoraires souscription Police Auto Flotte','AUTO','Comptant','001/001 — Police Auto Flotte',true,NOW(),NOW()),
    ('001','001','100','000','Avenant Police Auto','Honoraires souscription avenant Police Automobile','AUTO','Comptant','001/001 — Avenant Police Auto',true,NOW(),NOW()),
    ('004','001','001','000','Police Transport Voyage','Honoraires souscription Police Transport Voyage','TRANSPORT','Comptant','004/001 — Police Transport Voyage',true,NOW(),NOW()),
    ('004','001','002','000','Avenant Transport','Honoraires souscription Avenant Transport','TRANSPORT','Comptant','004/001 — Avenant Transport',true,NOW(),NOW()),
    ('004','001','100','000','Aliment Transport','Honoraires souscription Aliment Transport','TRANSPORT','Comptant','004/001 — Aliment Transport',true,NOW(),NOW()),
    ('002','002','001','000','Police Temporaire Décès','Honoraires souscription Police Temporaire Décès','VIE','Comptant','002/002 — Police Temporaire Décès',true,NOW(),NOW()),
    ('005','001','001','000','Police Vol','Honoraires souscription Police Vol','RISQUES DIVERS','Comptant','005/001 — Police Vol',true,NOW(),NOW()),
    ('005','002','001','000','Police Responsabilité','Honoraires souscription Police Responsabilité','RESPONSABILITES CIVILES','Comptant','005/002 — Police Responsabilité',true,NOW(),NOW()),
    ('005','003','001','000','Police Habitation','Honoraires souscription Police Habitation','RISQUES DIVERS','Comptant','005/003 — Police Habitation',true,NOW(),NOW()),
    ('005','003','002','000','Terme Habitation','Honoraires souscription Terme Habitation','RISQUES DIVERS','Termes','005/003 — Terme Habitation',true,NOW(),NOW()),
    ('005','002','002','000','Terme Responsabilité','Honoraires souscription Terme Responsabilité','RESPONSABILITES CIVILES','Termes','005/002 — Terme Responsabilité',true,NOW(),NOW()),
    ('005','004','001','000','Police Bris de Glaces','Honoraires souscription Police Bris de Glaces','RISQUES DIVERS','Comptant','005/004 — Police Bris de Glaces',true,NOW(),NOW()),
    ('005','005','001','000','Police Dégats des Eaux','Honoraires souscription Police Dégats des Eaux','RISQUES DIVERS','Comptant','005/005 — Police Dégats des Eaux',true,NOW(),NOW()),
    ('003','003','001','000','Police Incendie Simple','Honoraires souscription Police Incendie Simple','INCENDIE','Comptant','003/003 — Police Incendie Simple',true,NOW(),NOW()),
    ('003','004','001','000','Police Incendie Idustriel','Honoraires souscription Police Incendie Idustriel','INCENDIE','Comptant','003/004 — Police Incendie Idustriel',true,NOW(),NOW()),
    ('003','005','001','000','Police Multitrisque Pro.','Honoraires souscription Police Multirisque Professionnelle','MULTIRISQUES PROFESSIONNELLES','Comptant','003/005 — Police Multitrisque Pro.',true,NOW(),NOW()),
    ('003','006','001','000','Police Tous Risques Sauf','Honoraires souscription Police Tous Risques Sauf','MULTIRISQUES PROFESSIONNELLES','Comptant','003/006 — Police Tous Risques Sauf',true,NOW(),NOW()),
    ('009','001','001','000','Police RC Décénnale','Honoraires souscription Police RC Décénnale','RESPONSABILITES CIVILES','Comptant','009/001 — Police RC Décénnale',true,NOW(),NOW()),
    ('009','002','001','000','Police Bris de Machines','Honoraires souscription Police Bris de Machines','RISQUES SPECIAUX','Comptant','009/002 — Police Bris de Machines',true,NOW(),NOW()),
    ('009','003','001','000','Police T R Montage Ferme','Honoraires souscription Police Tous Risques Montages','RISQUES SPECIAUX','Comptant','009/003 — Police T R Montage Ferme',true,NOW(),NOW()),
    ('009','004','001','000','Police T R Chantiers Ferme','Honoraires souscription Police Tous Risques Chantiers','RISQUES SPECIAUX','Comptant','009/004 — Police T R Chantiers Ferme',true,NOW(),NOW()),
    ('009','005','001','000','Police Tous Risques Engins','Honoraires souscription Police Tous Risques Engins','RISQUES SPECIAUX','Comptant','009/005 — Police Tous Risques Engins',true,NOW(),NOW()),
    ('008','001','001','000','Police Groupe Maladie','Honoraires souscription police Maladie','MALADIE','Comptant','008/001 — Police Groupe Maladie',true,NOW(),NOW()),
    ('003','007','001','000','Police Multirisques Hotel','Honoraires souscription Multirisques Hotelier','MULTIRISQUES PROFESSIONNELLES','Comptant','003/007 — Police Multirisques Hotel',true,NOW(),NOW()),
    ('003','003','002','000','Terme Incendie Simple','Honoraires souscription Terme Incendie Simple','INCENDIE','Termes','003/003 — Terme Incendie Simple',true,NOW(),NOW()),
    ('003','004','002','000','Terme Incendie Industriel','Honoraires souscription Terme Incendie Industriel','INCENDIE','Termes','003/004 — Terme Incendie Industriel',true,NOW(),NOW()),
    ('003','005','002','000','Terme Multirisques Prof.','Honoraires souscription Terme Multirisques Professionnelles','MULTIRISQUES PROFESSIONNELLES','Termes','003/005 — Terme Multirisques Prof.',true,NOW(),NOW()),
    ('003','006','002','000','Terme Tous Risques Sauf','Honoraires souscription Terme Tous Risques Sauf','MULTIRISQUES PROFESSIONNELLES','Termes','003/006 — Terme Tous Risques Sauf',true,NOW(),NOW()),
    ('003','007','002','000','Terme Multirisques Hotel','Honoraires souscription Terme Multirisques Hotelier','MULTIRISQUES PROFESSIONNELLES','Termes','003/007 — Terme Multirisques Hotel',true,NOW(),NOW()),
    ('009','002','002','000','Terme Bris de Machines','Honoraires souscription Terme Bris de Machines','RISQUES SPECIAUX','Termes','009/002 — Terme Bris de Machines',true,NOW(),NOW()),
    ('009','005','002','000','Terme Tous Risques Engins','Honoraires souscription Terme Tous Risques Engins','RISQUES SPECIAUX','Termes','009/005 — Terme Tous Risques Engins',true,NOW(),NOW()),
    ('008','001','100','000','Avenant Maladie','Honoraires souscription avenant Maladie','MALADIE','Comptant','008/001 — Avenant Maladie',true,NOW(),NOW()),
    ('005','004','002','000','Terme Bris de Glaces','Honoraires souscription Terme Bris de Glaces','RISQUES DIVERS','Termes','005/004 — Terme Bris de Glaces',true,NOW(),NOW()),
    ('005','005','002','000','Terme Dégats des Eaux','Honoraires souscription Terme Dégats des Eaux','RISQUES DIVERS','Termes','005/005 — Terme Dégats des Eaux',true,NOW(),NOW()),
    ('100','100','100','000','Délivrance duplicata attestation','Honoraires délivrance duplicata attestation','AUTO','Comptant','100/100 — Délivrance duplicata attestation',true,NOW(),NOW()),
    ('100','100','101','000','Liquidation prime annuelle Responsabilités Civile','Honoraires Liquidation prime annuelle Responsabilités Civile','RESPONSABILITES CIVILES','Comptant','100/100 — Liquidation prime annuelle Responsabilités Civile',true,NOW(),NOW()),
    ('004','005','001','000','Police Corps Navire/Peche/Plaisance','Honoraires souscription Police Corps de Navire/Peche/Plaisance','CORPS DE PECHE/NAVIRE','Comptant','004/005 — Police Corps Navire/Peche/Plaisance',true,NOW(),NOW()),
    ('005','006','001','000','Police Accidents Corporels','Honoraires souscription Police Accidents Corporels','RISQUES DIVERS','Comptant','005/006 — Police Accidents Corporels',true,NOW(),NOW()),
    ('005','006','002','000','Terme Accidents Corporels','Honoraires souscription Terme police Accidents Corporels','RISQUES DIVERS','Termes','005/006 — Terme Accidents Corporels',true,NOW(),NOW()),
    ('001','001','003','000','Terme Automobile','Honoraires souscription Terme Automobile','AUTO','Termes','001/001 — Terme Automobile',true,NOW(),NOW()),
    ('009','001','002','000','Avenant Police RC Décénnale','Honoraires Avenant Police RC Décénnale','RESPONSABILITES CIVILES','Comptant','009/001 — Avenant Police RC Décénnale',true,NOW(),NOW()),
    ('100','100','102','000','Agrément acheteur','Frais enquête agrément acheteur',NULL,NULL,'100/100 — Agrément acheteur',true,NOW(),NOW()),
    ('100','100','103','000','Police Assistance Voyage','Honoraires souscription Police Assistance','ASSISTANCE','Comptant','100/100 — Police Assistance Voyage',true,NOW(),NOW()),
    ('005','001','002','000','Terme Vol','Honoraires souscription Terme Vol','RISQUES DIVERS','Termes','005/001 — Terme Vol',true,NOW(),NOW()),
    ('005','007','001','000','Police AMI','Honoraires souscription Police AMI','RISQUES DIVERS','Comptant','005/007 — Police AMI',true,NOW(),NOW()),
    ('005','007','002','000','Terme AMI','Honoraires soucription Terme AMI','RISQUES DIVERS','Termes','005/007 — Terme AMI',true,NOW(),NOW()),
    ('005','007','100','000','Avenant Multirisques AMI','Honoraires sousription Avenant AMI','RISQUES DIVERS','Comptant','005/007 — Avenant Multirisques AMI',true,NOW(),NOW()),
    ('001','001','500','000','Police Automobile Ferme','Honoraires souscription Police Auto Ferme','AUTO','Comptant','001/001 — Police Automobile Ferme',true,NOW(),NOW()),
    ('008','100','001','000','Police Santé Private','Honoraires souscription Police Santé Private','SANTE PREVOYANCE','Comptant','008/100 — Police Santé Private',true,NOW(),NOW()),
    ('100','100','105','000','Aliment Risques Commerciaux','Honoraires souscription Aliment Risques Commerciaux','RISQUES COMMERCIAUX','Comptant','100/100 — Aliment Risques Commerciaux',true,NOW(),NOW()),
    ('100','100','106','000','Police Risques Commeciaux','Honoraires souscription Police Risques Commeciaux','RISQUES COMMERCIAUX','Comptant','100/100 — Police Risques Commeciaux',true,NOW(),NOW()),
    ('003','004','003','000','Avenant Incendie Industriel','Honoraires souscription Avenant Incendie Industriel','INCENDIE','Comptant','003/004 — Avenant Incendie Industriel',true,NOW(),NOW()),
    ('005','002','003','000','Avenant Responsabilité','Honoraires souscription Avenant Responsabilité','RESPONSABILITES CIVILES','Comptant','005/002 — Avenant Responsabilité',true,NOW(),NOW()),
    ('009','009','050','000','Police Tous Risques Informatiques','Honoraires souscription Police TRI','RISQUES SPECIAUX','Comptant','009/009 — Police Tous Risques Informatiques',true,NOW(),NOW()),
    ('001','001','051','000','Police Auto/Tracteur Agricole','Honoraires souscription Police Auto/Tracteur Agr.','AUTO','Comptant','001/001 — Police Auto/Tracteur Agricole',true,NOW(),NOW()),
    ('001','001','004','000','Souscription Police Auto ES','Honoraires souscription Police Auto ES','AUTO','Comptant','001/001 — Souscription Police Auto ES',true,NOW(),NOW()),
    ('010','010','001','000','Police Vie','Honoraires sosucription Police Vie','VIE','Comptant','010/010 — Police Vie',true,NOW(),NOW())
ON CONFLICT (code_operation1, code_operation2) DO NOTHING;
COMMIT;
SELECT COUNT(*) AS types_importes FROM insurance_operation_type;
